// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatMSGLkGcIEtXKzvlvoGEEAHMb4d43p8',
    appId: '1:757500434994:web:9c8e9387ad4cc965a47a2b',
    messagingSenderId: '757500434994',
    projectId: 'dancingmonkey-6e76d',
    authDomain: 'dancingmonkey-6e76d.firebaseapp.com',
    storageBucket: 'dancingmonkey-6e76d.appspot.com',
    measurementId: 'G-E97KF0QP2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWcfVwsxSYti-Utb5iKXO6Xz5LbB8JW1U',
    appId: '1:757500434994:android:5c34cb10d2ac149ea47a2b',
    messagingSenderId: '757500434994',
    projectId: 'dancingmonkey-6e76d',
    storageBucket: 'dancingmonkey-6e76d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-spvfox1NUQAFFG0yzzH9ygakFbsbxg',
    appId: '1:757500434994:ios:a80777d70137acb3a47a2b',
    messagingSenderId: '757500434994',
    projectId: 'dancingmonkey-6e76d',
    storageBucket: 'dancingmonkey-6e76d.appspot.com',
    iosClientId: '757500434994-ifs4ki0mglc6hi5s4g2ja5r23jlh45gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.skadoodlem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs-spvfox1NUQAFFG0yzzH9ygakFbsbxg',
    appId: '1:757500434994:ios:a80777d70137acb3a47a2b',
    messagingSenderId: '757500434994',
    projectId: 'dancingmonkey-6e76d',
    storageBucket: 'dancingmonkey-6e76d.appspot.com',
    iosClientId: '757500434994-ifs4ki0mglc6hi5s4g2ja5r23jlh45gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.skadoodlem',
  );
}
